// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7hUhpTIpOqcPEyFIsaL0-Dd_LIlxL2yg',
    appId: '1:25561610093:web:e7161e39ae4abdad6a4c64',
    messagingSenderId: '25561610093',
    projectId: 'devart-c42a5',
    authDomain: 'devart-c42a5.firebaseapp.com',
    storageBucket: 'devart-c42a5.firebasestorage.app',
    measurementId: 'G-50T7627PJQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkfuyn48xjBW_oWbbsr2Dc6iaRXf3cnWo',
    appId: '1:25561610093:android:c3b957fe121263526a4c64',
    messagingSenderId: '25561610093',
    projectId: 'devart-c42a5',
    storageBucket: 'devart-c42a5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkO_N5srgIzfRiHwAbsfHkErwMEUkNJX8',
    appId: '1:25561610093:ios:938cf14ae6e037b16a4c64',
    messagingSenderId: '25561610093',
    projectId: 'devart-c42a5',
    storageBucket: 'devart-c42a5.firebasestorage.app',
    iosBundleId: 'com.example.devart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkO_N5srgIzfRiHwAbsfHkErwMEUkNJX8',
    appId: '1:25561610093:ios:938cf14ae6e037b16a4c64',
    messagingSenderId: '25561610093',
    projectId: 'devart-c42a5',
    storageBucket: 'devart-c42a5.firebasestorage.app',
    iosBundleId: 'com.example.devart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7hUhpTIpOqcPEyFIsaL0-Dd_LIlxL2yg',
    appId: '1:25561610093:web:e527eeafa90d6cb16a4c64',
    messagingSenderId: '25561610093',
    projectId: 'devart-c42a5',
    authDomain: 'devart-c42a5.firebaseapp.com',
    storageBucket: 'devart-c42a5.firebasestorage.app',
    measurementId: 'G-P9PGGB7FHX',
  );
}
